pipelines:
  file_es:
    input:
      type: file
    output:
      type: elasticsearch
      batch_flush_timeout: 200ms
      batch_size: 500 * 1
      connection_timeout: 30s
      endpoints:
        - http://localhost:9200
      fatal_on_failed_insert: true
      strict: false
      index_format: seq-db
      retry: 1
      retention: 1s
      workers_count: 1
      username: elastic
      password: password
