name: CD

on:
  release:
    types: published

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        image:
          - name: "ubuntu:latest"
            suffix: ""
          - name: "ubuntu:22.04"
            suffix: "-ubuntu22.04"
          - name: "ubuntu:20.04"
            suffix: "-ubuntu20.04"
          - name: "ubuntu:18.04"
            suffix: "-ubuntu18.04"
          - name: "alpine"
            suffix: "-alpine"
          - name: "scratch"
            suffix: "-scratch"
            dockerfile: "./build/package/Dockerfile.scratch"
          # RedHat-based distributions
          - name: "rockylinux:9"
            suffix: "-rocky9"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false

      - name: Build and push
        id: docker-build
        uses: docker/build-push-action@v6
        with:
          push: true
          file: ${{ matrix.image.dockerfile || './build/package/Dockerfile' }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            VERSION=${{ github.ref_name }}
            APP_IMAGE=${{ matrix.image.name }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.ref_name }}${{ matrix.image.suffix }}
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest${{ matrix.image.suffix }}

  build-playground:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false

      - name: Build and push
        id: docker-build
        uses: docker/build-push-action@v4
        with:
          push: true
          file: ./build/package/Dockerfile_playground
          platforms: linux/amd64,linux/arm64
          build-args: |
            VERSION=${{ github.ref_name }}
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-playground:${{ github.ref_name }}
